# Generated by Django 3.0.5 on 2020-04-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.FileField(default=False, upload_to=''),
            preserve_default=False,
        ),
    ]
